name: example
description: Demo app para testar my_error_handler
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  acta:
    path: ../   # aponta pro package local
