name: acta
description: "A tool for application management that captures events and errors in a structured and extensible way."
version: 0.0.3

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Optional: add these ONLY if you plan to re-export or use their reporters by default.
  # For now, **do not** list them here to keep the core lightweight.
  # firebase_crashlytics: ^5.0.0
  # cloud_firestore: ^6.0.0
  # firebase_core: ^4.0.0
  # sentry_flutter: ^9.6.0
  mongo_dart: ^0.10.5
  http: ^1.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

repository:  https://github.com/pampu-software/acta